name = "growicms"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "growicms-db"
database_id = "1778ee73-cadc-4ffe-b655-fd62a383fd06"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "growicms-storage"

[[kv_namespaces]]
binding = "CACHE"
id = "4e78881500e94771ba9fde69db933fa3"

[vars]
JWT_CLAVE_SECRETA = "growicms-secreta-super-segura-cambia-en-produccion"
TWILIO_CUENTA_SID = ""
TWILIO_AUTH_TOKEN = ""
TWILIO_NUMERO_ORIGEN = ""
